on:
  release:
    types: [published]

jobs:
  publish:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo publish
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
