name: Build project

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    # Avoid running twice the action if it's triggered by a push on a PR from a branch on the repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    container:
      image: rocq/rocq-prover:9.0
      # This is a workaround a "bug" on the checkout action,
      # see https://github.com/actions/checkout/issues/956
      options: --user root

    steps:
      - uses: actions/checkout@master
      - name: "Run coq-community/docker-coq-action@v1 with debian:10"
        uses: coq-community/docker-coq-action@v1
        with:
          # Explanation for the permission issue:
          # https://github.com/coq-community/docker-coq-action#permissions
          before_script: |
            startGroup "Workaround permission issue"
              sudo chown -R 1000:1000 .  # <--
            endGroup
          install: |
            startGroup "Install dependencies"
              opam update -y
              ./install.sh -y
            endGroup
          script: |
            startGroup "Build project"
              make -j 4
            endGroup
          uninstall: |
            startGroup "Clean project"
              make clean
            endGroup

      - name: Revert permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 . # <--
