version: 2
updates:
  # General updates (run monthly)
  - package-ecosystem: "cargo"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "monthly"

  # Security updates (run daily)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*" # Ensure only security updates are included
    commit-message:
      prefix: "security"
